# Docker Compose profiles:
# - Default (no profile): Starts chipos-server, chipos-mcp, and chipos-frontend
# - Agents are opt-in: chipos-agents starts only with the "agents" profile
# Usage:
#   docker compose up                        # Starts server, mcp, frontend (agents disabled)
#   docker compose --profile agents up -d    # Also starts chipos-agents

services:
  # Server Service (FastAPI + Socket.IO + Crawling)
  chipos-server:
    build:
      context: ./python
      dockerfile: Dockerfile.server
      args:
        BUILDKIT_INLINE_CACHE: 1
        CHIPOS_SERVER_PORT: ${CHIPOS_SERVER_PORT:-8181}
    container_name: chipos-server
    ports:
      - "${CHIPOS_SERVER_PORT:-8181}:${CHIPOS_SERVER_PORT:-8181}"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN:-}
      - SERVICE_DISCOVERY_MODE=docker_compose
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CHIPOS_SERVER_PORT=${CHIPOS_SERVER_PORT:-8181}
      - CHIPOS_MCP_PORT=${CHIPOS_MCP_PORT:-8051}
      - CHIPOS_AGENTS_PORT=${CHIPOS_AGENTS_PORT:-8052}
      - AGENTS_ENABLED=${AGENTS_ENABLED:-false}
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket for MCP container control
      - ./python/src:/app/src # Mount source code for hot reload
      - ./python/tests:/app/tests # Mount tests for UI test execution
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "src.server.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "${CHIPOS_SERVER_PORT:-8181}",
        "--reload",
      ]
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:${CHIPOS_SERVER_PORT:-8181}/health'')"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Lightweight MCP Server Service (HTTP-based)
  chipos-mcp:
    build:
      context: ./python
      dockerfile: Dockerfile.mcp
      args:
        BUILDKIT_INLINE_CACHE: 1
        CHIPOS_MCP_PORT: ${CHIPOS_MCP_PORT:-8051}
    container_name: chipos-mcp
    ports:
      - "${CHIPOS_MCP_PORT:-8051}:${CHIPOS_MCP_PORT:-8051}"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN:-}
      - SERVICE_DISCOVERY_MODE=docker_compose
      - TRANSPORT=sse
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # MCP needs to know where to find other services
      - API_SERVICE_URL=http://chipos-server:${CHIPOS_SERVER_PORT:-8181}
      - AGENTS_ENABLED=${AGENTS_ENABLED:-false}
      - AGENTS_SERVICE_URL=${AGENTS_SERVICE_URL:-http://chipos-agents:${CHIPOS_AGENTS_PORT:-8052}}
      - CHIPOS_MCP_PORT=${CHIPOS_MCP_PORT:-8051}
      - CHIPOS_SERVER_PORT=${CHIPOS_SERVER_PORT:-8181}
      - CHIPOS_AGENTS_PORT=${CHIPOS_AGENTS_PORT:-8052}
    networks:
      - app-network
    depends_on:
      chipos-server:
        condition: service_healthy
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'python -c "import socket; s=socket.socket(); s.connect((''localhost'', ${CHIPOS_MCP_PORT:-8051})); s.close()"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # Give dependencies time to start

  # AI Agents Service (ML/Reranking)
  chipos-agents:
    profiles:
      - agents  # Only starts when explicitly using --profile agents
    build:
      context: ./python
      dockerfile: Dockerfile.agents
      args:
        BUILDKIT_INLINE_CACHE: 1
        CHIPOS_AGENTS_PORT: ${CHIPOS_AGENTS_PORT:-8052}
    container_name: chipos-agents
    ports:
      - "${CHIPOS_AGENTS_PORT:-8052}:${CHIPOS_AGENTS_PORT:-8052}"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN:-}
      - SERVICE_DISCOVERY_MODE=docker_compose
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CHIPOS_AGENTS_PORT=${CHIPOS_AGENTS_PORT:-8052}
      - CHIPOS_SERVER_PORT=${CHIPOS_SERVER_PORT:-8181}
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:${CHIPOS_AGENTS_PORT:-8052}/health'')"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  chipos-frontend:
    build: ./chipos-ui-main
    container_name: chipos-ui
    ports:
      - "${CHIPOS_UI_PORT:-3737}:3737"
    environment:
      - VITE_API_URL=http://${HOST:-localhost}:${CHIPOS_SERVER_PORT:-8181}
      - VITE_CHIPOS_SERVER_PORT=${CHIPOS_SERVER_PORT:-8181}
      - CHIPOS_SERVER_PORT=${CHIPOS_SERVER_PORT:-8181}
      - HOST=${HOST:-localhost}
      - PROD=${PROD:-false}
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS:-}
      - VITE_SHOW_DEVTOOLS=${VITE_SHOW_DEVTOOLS:-false}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3737"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./chipos-ui-main/src:/app/src
      - ./chipos-ui-main/public:/app/public
    depends_on:
      chipos-server:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
